version: '3.8'

services:
  db:
    image: postgres:15
    container_name: service-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
    ports:
      - "5433:5432"
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: fastapi_projects_dashboard
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "80:80"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
