[project]
name = "final_project"
description = "Project management/profiles dashboard - a service to create, update, share, and delete projects information(details, attached documents)"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name="Simon Muncan",email ="simon_muncan@epam.com"}
]
dynamic = ["dependencies"]

[project.urls]
Homepage = "http://localhost/"

[project.setuptools.dynamic]
dependencies = {file =["requirements.txt"]}

[tool.pdm.build]
source-includes = [
    "tests/",
    "requirements*.txt"
]