[project]
name = "Final project"
description = "Project management/profiles dashboard - a service to create, update, share, and delete projects information(details, attached documents)"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name="Simon Muncan",email ="simon_muncan@epa.com"}
]
[project.urls]
Homepage = "http://localhost/"

[project.optional-dependencies]
standard = [
    "fastapi[standard] >= 0.115.0",
    "uvicorn>=0.34.0"
]
all =[
    "fastapi[standard] >= 0.115.0",
    "uvicorn>=0.34.0"
]

[tool.pdm.build]
source-includes = [
    "tests/",
    "requirements*.txt"
]