"""Seccond revision

Revision ID: 822ad612611f
Revises: 5ed0d2ab5968
Create Date: 2025-02-25 10:55:25.036967

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "822ad612611f"
down_revision: Union[str, None] = "5ed0d2ab5968"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_project", "project_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("user_project", "user_id", existing_type=sa.UUID(), nullable=False)
    op.alter_column("user_project", "is_admin", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_project", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("user_project", "user_id", existing_type=sa.UUID(), nullable=True)
    op.alter_column("user_project", "project_id", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###
