"""Third revision

Revision ID: cf8315ced0e3
Revises: 822ad612611f
Create Date: 2025-02-26 11:46:12.824603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8315ced0e3'
down_revision: Union[str, None] = '822ad612611f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_project', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('_unique_admin_per_project', 'user_project', type_='unique')
    op.create_index('one_admin_per_project', 'user_project', ['project_id'], unique=True, postgresql_where=sa.text('is_admin = true'))
    op.drop_column('user_project', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_index('one_admin_per_project', table_name='user_project', postgresql_where=sa.text('is_admin = true'))
    op.create_unique_constraint('_unique_admin_per_project', 'user_project', ['project_id', 'is_admin'])
    op.alter_column('user_project', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
