name: CD

on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker image
        run: docker build -t my-app:latest .
